# Override MCUboot auto-calculation for max sectors because Renode's
# mocked 1MB flash chip has 256 sectors, which exceeds the default 118 sectors.
CONFIG_BOOT_MAX_IMG_SECTORS_AUTO=n
CONFIG_BOOT_MAX_IMG_SECTORS=256
