CONFIG_PRINTK=y
CONFIG_DISPLAY=y
CONFIG_I2C=y
CONFIG_CHARACTER_FRAMEBUFFER=y
CONFIG_SSD1306=y
CONFIG_HEAP_MEM_POOL_SIZE=16384

# Enable Bluetooth for OTA
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="F91_Jepler"

# Tell Zephyr to compile for MCUboot (offsets the firmware in flash)
CONFIG_BOOTLOADER_MCUBOOT=y

# Enable Flash and Image Management
CONFIG_FLASH=y
CONFIG_IMG_MANAGER=y

# Enable SMP (Simple Management Protocol) OTA Server
CONFIG_ZCBOR=y
CONFIG_STREAM_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NET_BUF=y
CONFIG_MCUMGR=y
CONFIG_MCUMGR_TRANSPORT_BT=y
CONFIG_MCUMGR_GRP_OS=y
CONFIG_MCUMGR_GRP_IMG=y
